// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: orchestrator.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED         Tier = 0
	Tier_TIER_T0_BROWSER          Tier = 1
	Tier_TIER_T1_SHARED_CONTAINER Tier = 2
	Tier_TIER_T2_ISOLATED_MICROVM Tier = 3
	Tier_TIER_T3_CLOUD_ACCOUNT    Tier = 4
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_T0_BROWSER",
		2: "TIER_T1_SHARED_CONTAINER",
		3: "TIER_T2_ISOLATED_MICROVM",
		4: "TIER_T3_CLOUD_ACCOUNT",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED":         0,
		"TIER_T0_BROWSER":          1,
		"TIER_T1_SHARED_CONTAINER": 2,
		"TIER_T2_ISOLATED_MICROVM": 3,
		"TIER_T3_CLOUD_ACCOUNT":    4,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type EnvironmentStatus int32

const (
	EnvironmentStatus_ENVIRONMENT_STATUS_UNSPECIFIED      EnvironmentStatus = 0
	EnvironmentStatus_ENVIRONMENT_STATUS_PROVISIONING     EnvironmentStatus = 1
	EnvironmentStatus_ENVIRONMENT_STATUS_READY            EnvironmentStatus = 2
	EnvironmentStatus_ENVIRONMENT_STATUS_PROVISION_FAILED EnvironmentStatus = 3
	EnvironmentStatus_ENVIRONMENT_STATUS_IDLE             EnvironmentStatus = 4
	EnvironmentStatus_ENVIRONMENT_STATUS_DESTROYED        EnvironmentStatus = 5
)

// Enum value maps for EnvironmentStatus.
var (
	EnvironmentStatus_name = map[int32]string{
		0: "ENVIRONMENT_STATUS_UNSPECIFIED",
		1: "ENVIRONMENT_STATUS_PROVISIONING",
		2: "ENVIRONMENT_STATUS_READY",
		3: "ENVIRONMENT_STATUS_PROVISION_FAILED",
		4: "ENVIRONMENT_STATUS_IDLE",
		5: "ENVIRONMENT_STATUS_DESTROYED",
	}
	EnvironmentStatus_value = map[string]int32{
		"ENVIRONMENT_STATUS_UNSPECIFIED":      0,
		"ENVIRONMENT_STATUS_PROVISIONING":     1,
		"ENVIRONMENT_STATUS_READY":            2,
		"ENVIRONMENT_STATUS_PROVISION_FAILED": 3,
		"ENVIRONMENT_STATUS_IDLE":             4,
		"ENVIRONMENT_STATUS_DESTROYED":        5,
	}
)

func (x EnvironmentStatus) Enum() *EnvironmentStatus {
	p := new(EnvironmentStatus)
	*p = x
	return p
}

func (x EnvironmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvironmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[1].Descriptor()
}

func (EnvironmentStatus) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[1]
}

func (x EnvironmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvironmentStatus.Descriptor instead.
func (EnvironmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // e.g. "2"
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"` // e.g. "4Gi"
	Disk          string                 `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`     // e.g. "10Gi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSpec) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceSpec) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceSpec) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

type FixtureRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FixtureId     string                 `protobuf:"bytes,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureRef) Reset() {
	*x = FixtureRef{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureRef) ProtoMessage() {}

func (x *FixtureRef) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureRef.ProtoReflect.Descriptor instead.
func (*FixtureRef) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *FixtureRef) GetFixtureId() string {
	if x != nil {
		return x.FixtureId
	}
	return ""
}

func (x *FixtureRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ProvisionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttemptId          string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"` // idempotency + correlation key, doc §13.5 #1
	BlueprintId        string                 `protobuf:"bytes,2,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	BlueprintVersion   string                 `protobuf:"bytes,3,opt,name=blueprint_version,json=blueprintVersion,proto3" json:"blueprint_version,omitempty"`
	Tier               Tier                   `protobuf:"varint,4,opt,name=tier,proto3,enum=practiceengine.orchestrator.v1.Tier" json:"tier,omitempty"`
	Resources          *ResourceSpec          `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Fixtures           []*FixtureRef          `protobuf:"bytes,6,rep,name=fixtures,proto3" json:"fixtures,omitempty"`
	TtlMinutes         int32                  `protobuf:"varint,7,opt,name=ttl_minutes,json=ttlMinutes,proto3" json:"ttl_minutes,omitempty"`
	IdleTimeoutMinutes int32                  `protobuf:"varint,8,opt,name=idle_timeout_minutes,json=idleTimeoutMinutes,proto3" json:"idle_timeout_minutes,omitempty"`
	NetworkPolicy      string                 `protobuf:"bytes,9,opt,name=network_policy,json=networkPolicy,proto3" json:"network_policy,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ProvisionRequest) GetBlueprintId() string {
	if x != nil {
		return x.BlueprintId
	}
	return ""
}

func (x *ProvisionRequest) GetBlueprintVersion() string {
	if x != nil {
		return x.BlueprintVersion
	}
	return ""
}

func (x *ProvisionRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *ProvisionRequest) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ProvisionRequest) GetFixtures() []*FixtureRef {
	if x != nil {
		return x.Fixtures
	}
	return nil
}

func (x *ProvisionRequest) GetTtlMinutes() int32 {
	if x != nil {
		return x.TtlMinutes
	}
	return 0
}

func (x *ProvisionRequest) GetIdleTimeoutMinutes() int32 {
	if x != nil {
		return x.IdleTimeoutMinutes
	}
	return 0
}

func (x *ProvisionRequest) GetNetworkPolicy() string {
	if x != nil {
		return x.NetworkPolicy
	}
	return ""
}

func (x *ProvisionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Status        EnvironmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=practiceengine.orchestrator.v1.EnvironmentStatus" json:"status,omitempty"`
	// Populated once READY; absent while PROVISIONING (caller waits on events).
	Endpoints     *ConnectResponse `protobuf:"bytes,3,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ProvisionResponse) GetStatus() EnvironmentStatus {
	if x != nil {
		return x.Status
	}
	return EnvironmentStatus_ENVIRONMENT_STATUS_UNSPECIFIED
}

func (x *ProvisionResponse) GetEndpoints() *ConnectResponse {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type ConnectResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TerminalWsUrl      string                 `protobuf:"bytes,1,opt,name=terminal_ws_url,json=terminalWsUrl,proto3" json:"terminal_ws_url,omitempty"`
	EditorUrl          string                 `protobuf:"bytes,2,opt,name=editor_url,json=editorUrl,proto3" json:"editor_url,omitempty"`
	PreviewUrlTemplate string                 `protobuf:"bytes,3,opt,name=preview_url_template,json=previewUrlTemplate,proto3" json:"preview_url_template,omitempty"` // {env_id}-{port}.preview.platform.io
	SessionToken       string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`                     // scoped, short-lived
	ExpiresAt          string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                              // RFC3339
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectResponse) GetTerminalWsUrl() string {
	if x != nil {
		return x.TerminalWsUrl
	}
	return ""
}

func (x *ConnectResponse) GetEditorUrl() string {
	if x != nil {
		return x.EditorUrl
	}
	return ""
}

func (x *ConnectResponse) GetPreviewUrlTemplate() string {
	if x != nil {
		return x.PreviewUrlTemplate
	}
	return ""
}

func (x *ConnectResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ConnectResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // "suspend" | "periodic" | "pre_reset" | "preemption"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *SnapshotRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *SnapshotRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageUri    string                 `protobuf:"bytes,2,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"` // attempts/{id}/snapshots/{ts}.tar.zst
	Bytes         int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotResponse) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *SnapshotResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type RestoreRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttemptId        string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	SnapshotId       string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	BlueprintId      string                 `protobuf:"bytes,3,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	BlueprintVersion string                 `protobuf:"bytes,4,opt,name=blueprint_version,json=blueprintVersion,proto3" json:"blueprint_version,omitempty"`
	Tier             Tier                   `protobuf:"varint,5,opt,name=tier,proto3,enum=practiceengine.orchestrator.v1.Tier" json:"tier,omitempty"`
	Resources        *ResourceSpec          `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RestoreRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *RestoreRequest) GetBlueprintId() string {
	if x != nil {
		return x.BlueprintId
	}
	return ""
}

func (x *RestoreRequest) GetBlueprintVersion() string {
	if x != nil {
		return x.BlueprintVersion
	}
	return ""
}

func (x *RestoreRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *RestoreRequest) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

type MintCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 300s default per §6.2 execution rules
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`                            // e.g. "k8s.read_only", "cloud.read_only"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintCredentialsRequest) Reset() {
	*x = MintCredentialsRequest{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCredentialsRequest) ProtoMessage() {}

func (x *MintCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCredentialsRequest.ProtoReflect.Descriptor instead.
func (*MintCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *MintCredentialsRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *MintCredentialsRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *MintCredentialsRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type MintCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialRef string                 `protobuf:"bytes,1,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"` // opaque handle, never the raw secret in logs
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintCredentialsResponse) Reset() {
	*x = MintCredentialsResponse{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCredentialsResponse) ProtoMessage() {}

func (x *MintCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCredentialsResponse.ProtoReflect.Descriptor instead.
func (*MintCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *MintCredentialsResponse) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *MintCredentialsResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "submit" | "idle" | "ttl" | "budget" | "reaper" | "admin"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *DestroyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DestroyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlreadyDestroyed bool                   `protobuf:"varint,1,opt,name=already_destroyed,json=alreadyDestroyed,proto3" json:"already_destroyed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *DestroyResponse) GetAlreadyDestroyed() bool {
	if x != nil {
		return x.AlreadyDestroyed
	}
	return false
}

type InjectFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	FaultId       string                 `protobuf:"bytes,2,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	FaultVersion  string                 `protobuf:"bytes,3,opt,name=fault_version,json=faultVersion,proto3" json:"fault_version,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFaultRequest) Reset() {
	*x = InjectFaultRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFaultRequest) ProtoMessage() {}

func (x *InjectFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFaultRequest.ProtoReflect.Descriptor instead.
func (*InjectFaultRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *InjectFaultRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *InjectFaultRequest) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *InjectFaultRequest) GetFaultVersion() string {
	if x != nil {
		return x.FaultVersion
	}
	return ""
}

func (x *InjectFaultRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type InjectFaultResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Applied         bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	SymptomVerified bool                   `protobuf:"varint,2,opt,name=symptom_verified,json=symptomVerified,proto3" json:"symptom_verified,omitempty"` // health-recheck confirms authored symptom manifested
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InjectFaultResponse) Reset() {
	*x = InjectFaultResponse{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFaultResponse) ProtoMessage() {}

func (x *InjectFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFaultResponse.ProtoReflect.Descriptor instead.
func (*InjectFaultResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *InjectFaultResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *InjectFaultResponse) GetSymptomVerified() bool {
	if x != nil {
		return x.SymptomVerified
	}
	return false
}

type CaptureBaselineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	SnapshotKey   string                 `protobuf:"bytes,2,opt,name=snapshot_key,json=snapshotKey,proto3" json:"snapshot_key,omitempty"` // content-authored label, e.g. "baseline.other-services" (doc §7.3 worked example)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureBaselineRequest) Reset() {
	*x = CaptureBaselineRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureBaselineRequest) ProtoMessage() {}

func (x *CaptureBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureBaselineRequest.ProtoReflect.Descriptor instead.
func (*CaptureBaselineRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *CaptureBaselineRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CaptureBaselineRequest) GetSnapshotKey() string {
	if x != nil {
		return x.SnapshotKey
	}
	return ""
}

type CaptureBaselineResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotKey       string                 `protobuf:"bytes,1,opt,name=snapshot_key,json=snapshotKey,proto3" json:"snapshot_key,omitempty"`
	CapturedAt        string                 `protobuf:"bytes,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`                       // RFC3339
	ResourcesCaptured int32                  `protobuf:"varint,3,opt,name=resources_captured,json=resourcesCaptured,proto3" json:"resources_captured,omitempty"` // count of Deployments+Services+Pods included in the health matrix
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaptureBaselineResponse) Reset() {
	*x = CaptureBaselineResponse{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureBaselineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureBaselineResponse) ProtoMessage() {}

func (x *CaptureBaselineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureBaselineResponse.ProtoReflect.Descriptor instead.
func (*CaptureBaselineResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *CaptureBaselineResponse) GetSnapshotKey() string {
	if x != nil {
		return x.SnapshotKey
	}
	return ""
}

func (x *CaptureBaselineResponse) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

func (x *CaptureBaselineResponse) GetResourcesCaptured() int32 {
	if x != nil {
		return x.ResourcesCaptured
	}
	return 0
}

type CheckRegressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	SnapshotKey   string                 `protobuf:"bytes,2,opt,name=snapshot_key,json=snapshotKey,proto3" json:"snapshot_key,omitempty"` // must match a prior CaptureBaseline call for this environment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegressionRequest) Reset() {
	*x = CheckRegressionRequest{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegressionRequest) ProtoMessage() {}

func (x *CheckRegressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegressionRequest.ProtoReflect.Descriptor instead.
func (*CheckRegressionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *CheckRegressionRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CheckRegressionRequest) GetSnapshotKey() string {
	if x != nil {
		return x.SnapshotKey
	}
	return ""
}

type CheckRegressionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RegressionFound    bool                   `protobuf:"varint,1,opt,name=regression_found,json=regressionFound,proto3" json:"regression_found,omitempty"`
	RegressedResources []string               `protobuf:"bytes,2,rep,name=regressed_resources,json=regressedResources,proto3" json:"regressed_resources,omitempty"` // e.g. "Deployment/payments-api: readyReplicas dropped 3 -> 0"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckRegressionResponse) Reset() {
	*x = CheckRegressionResponse{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegressionResponse) ProtoMessage() {}

func (x *CheckRegressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegressionResponse.ProtoReflect.Descriptor instead.
func (*CheckRegressionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *CheckRegressionResponse) GetRegressionFound() bool {
	if x != nil {
		return x.RegressionFound
	}
	return false
}

func (x *CheckRegressionResponse) GetRegressedResources() []string {
	if x != nil {
		return x.RegressedResources
	}
	return nil
}

type ExecValidatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	ValidatorType string                 `protobuf:"bytes,3,opt,name=validator_type,json=validatorType,proto3" json:"validator_type,omitempty"` // SHELL_ASSERT | SHELL_JSON | FILE_EXISTS | FILE_CONTENT | FILE_PARSE | K8S_ASSERT
	Run           string                 `protobuf:"bytes,4,opt,name=run,proto3" json:"run,omitempty"`                                          // command / file path, per validator_type -- see contracts/activity_spec.schema.json's ValidatorSpec
	ExpectJson    string                 `protobuf:"bytes,5,opt,name=expect_json,json=expectJson,proto3" json:"expect_json,omitempty"`          // ValidatorSpec.expect, JSON-encoded -- shape varies per validator_type, not modeled field-by-field in proto
	TimeoutMs     int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`            // 0 = use the executor's own default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecValidatorRequest) Reset() {
	*x = ExecValidatorRequest{}
	mi := &file_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecValidatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecValidatorRequest) ProtoMessage() {}

func (x *ExecValidatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecValidatorRequest.ProtoReflect.Descriptor instead.
func (*ExecValidatorRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *ExecValidatorRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ExecValidatorRequest) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *ExecValidatorRequest) GetValidatorType() string {
	if x != nil {
		return x.ValidatorType
	}
	return ""
}

func (x *ExecValidatorRequest) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *ExecValidatorRequest) GetExpectJson() string {
	if x != nil {
		return x.ExpectJson
	}
	return ""
}

func (x *ExecValidatorRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecValidatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // PASS | FAIL | ERROR
	ObservedJson  string                 `protobuf:"bytes,2,opt,name=observed_json,json=observedJson,proto3" json:"observed_json,omitempty"` // JSON-encoded observed value, empty on ERROR
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // populated only when status == ERROR
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecValidatorResponse) Reset() {
	*x = ExecValidatorResponse{}
	mi := &file_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecValidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecValidatorResponse) ProtoMessage() {}

func (x *ExecValidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecValidatorResponse.ProtoReflect.Descriptor instead.
func (*ExecValidatorResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *ExecValidatorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecValidatorResponse) GetObservedJson() string {
	if x != nil {
		return x.ObservedJson
	}
	return ""
}

func (x *ExecValidatorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecValidatorResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecShellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                       // run via `/bin/bash -c`, same as ExecValidator's SHELL_* types
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 0 = use the executor's own default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecShellRequest) Reset() {
	*x = ExecShellRequest{}
	mi := &file_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellRequest) ProtoMessage() {}

func (x *ExecShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecShellRequest.ProtoReflect.Descriptor instead.
func (*ExecShellRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *ExecShellRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ExecShellRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecShellRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecShellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // populated only on infrastructure-level failure (pod unreachable etc), not a nonzero exit code
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecShellResponse) Reset() {
	*x = ExecShellResponse{}
	mi := &file_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellResponse) ProtoMessage() {}

func (x *ExecShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecShellResponse.ProtoReflect.Descriptor instead.
func (*ExecShellResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *ExecShellResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecShellResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecShellResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecShellResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecShellResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x1epracticeengine.orchestrator.v1\"L\n" +
	"\fResourceSpec\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\tR\x04disk\"E\n" +
	"\n" +
	"FixtureRef\x12\x1d\n" +
	"\n" +
	"fixture_id\x18\x01 \x01(\tR\tfixtureId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf2\x03\n" +
	"\x10ProvisionRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12!\n" +
	"\fblueprint_id\x18\x02 \x01(\tR\vblueprintId\x12+\n" +
	"\x11blueprint_version\x18\x03 \x01(\tR\x10blueprintVersion\x128\n" +
	"\x04tier\x18\x04 \x01(\x0e2$.practiceengine.orchestrator.v1.TierR\x04tier\x12J\n" +
	"\tresources\x18\x05 \x01(\v2,.practiceengine.orchestrator.v1.ResourceSpecR\tresources\x12F\n" +
	"\bfixtures\x18\x06 \x03(\v2*.practiceengine.orchestrator.v1.FixtureRefR\bfixtures\x12\x1f\n" +
	"\vttl_minutes\x18\a \x01(\x05R\n" +
	"ttlMinutes\x120\n" +
	"\x14idle_timeout_minutes\x18\b \x01(\x05R\x12idleTimeoutMinutes\x12%\n" +
	"\x0enetwork_policy\x18\t \x01(\tR\rnetworkPolicy\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\"\xd4\x01\n" +
	"\x11ProvisionResponse\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12I\n" +
	"\x06status\x18\x02 \x01(\x0e21.practiceengine.orchestrator.v1.EnvironmentStatusR\x06status\x12M\n" +
	"\tendpoints\x18\x03 \x01(\v2/.practiceengine.orchestrator.v1.ConnectResponseR\tendpoints\"7\n" +
	"\x0eConnectRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"\xce\x01\n" +
	"\x0fConnectResponse\x12&\n" +
	"\x0fterminal_ws_url\x18\x01 \x01(\tR\rterminalWsUrl\x12\x1d\n" +
	"\n" +
	"editor_url\x18\x02 \x01(\tR\teditorUrl\x120\n" +
	"\x14preview_url_template\x18\x03 \x01(\tR\x12previewUrlTemplate\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"o\n" +
	"\x0fSnapshotRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"j\n" +
	"\x10SnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1f\n" +
	"\vstorage_uri\x18\x02 \x01(\tR\n" +
	"storageUri\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\"\xa6\x02\n" +
	"\x0eRestoreRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12!\n" +
	"\fblueprint_id\x18\x03 \x01(\tR\vblueprintId\x12+\n" +
	"\x11blueprint_version\x18\x04 \x01(\tR\x10blueprintVersion\x128\n" +
	"\x04tier\x18\x05 \x01(\x0e2$.practiceengine.orchestrator.v1.TierR\x04tier\x12J\n" +
	"\tresources\x18\x06 \x01(\v2,.practiceengine.orchestrator.v1.ResourceSpecR\tresources\"x\n" +
	"\x16MintCredentialsRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x05R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"_\n" +
	"\x17MintCredentialsResponse\x12%\n" +
	"\x0ecredential_ref\x18\x01 \x01(\tR\rcredentialRef\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"O\n" +
	"\x0eDestroyRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\">\n" +
	"\x0fDestroyResponse\x12+\n" +
	"\x11already_destroyed\x18\x01 \x01(\bR\x10alreadyDestroyed\"\x8e\x02\n" +
	"\x12InjectFaultRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x19\n" +
	"\bfault_id\x18\x02 \x01(\tR\afaultId\x12#\n" +
	"\rfault_version\x18\x03 \x01(\tR\ffaultVersion\x12V\n" +
	"\x06params\x18\x04 \x03(\v2>.practiceengine.orchestrator.v1.InjectFaultRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x13InjectFaultResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12)\n" +
	"\x10symptom_verified\x18\x02 \x01(\bR\x0fsymptomVerified\"b\n" +
	"\x16CaptureBaselineRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12!\n" +
	"\fsnapshot_key\x18\x02 \x01(\tR\vsnapshotKey\"\x8c\x01\n" +
	"\x17CaptureBaselineResponse\x12!\n" +
	"\fsnapshot_key\x18\x01 \x01(\tR\vsnapshotKey\x12\x1f\n" +
	"\vcaptured_at\x18\x02 \x01(\tR\n" +
	"capturedAt\x12-\n" +
	"\x12resources_captured\x18\x03 \x01(\x05R\x11resourcesCaptured\"b\n" +
	"\x16CheckRegressionRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12!\n" +
	"\fsnapshot_key\x18\x02 \x01(\tR\vsnapshotKey\"u\n" +
	"\x17CheckRegressionResponse\x12)\n" +
	"\x10regression_found\x18\x01 \x01(\bR\x0fregressionFound\x12/\n" +
	"\x13regressed_resources\x18\x02 \x03(\tR\x12regressedResources\"\xd9\x01\n" +
	"\x14ExecValidatorRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12%\n" +
	"\x0evalidator_type\x18\x03 \x01(\tR\rvalidatorType\x12\x10\n" +
	"\x03run\x18\x04 \x01(\tR\x03run\x12\x1f\n" +
	"\vexpect_json\x18\x05 \x01(\tR\n" +
	"expectJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\"\x9a\x01\n" +
	"\x15ExecValidatorResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\robserved_json\x18\x02 \x01(\tR\fobservedJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\"r\n" +
	"\x10ExecShellRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\xa6\x01\n" +
	"\x11ExecShellResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs*\x88\x01\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTIER_T0_BROWSER\x10\x01\x12\x1c\n" +
	"\x18TIER_T1_SHARED_CONTAINER\x10\x02\x12\x1c\n" +
	"\x18TIER_T2_ISOLATED_MICROVM\x10\x03\x12\x19\n" +
	"\x15TIER_T3_CLOUD_ACCOUNT\x10\x04*\xe2\x01\n" +
	"\x11EnvironmentStatus\x12\"\n" +
	"\x1eENVIRONMENT_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fENVIRONMENT_STATUS_PROVISIONING\x10\x01\x12\x1c\n" +
	"\x18ENVIRONMENT_STATUS_READY\x10\x02\x12'\n" +
	"#ENVIRONMENT_STATUS_PROVISION_FAILED\x10\x03\x12\x1b\n" +
	"\x17ENVIRONMENT_STATUS_IDLE\x10\x04\x12 \n" +
	"\x1cENVIRONMENT_STATUS_DESTROYED\x10\x052\xc0\n" +
	"\n" +
	"\x17EnvironmentOrchestrator\x12p\n" +
	"\tProvision\x120.practiceengine.orchestrator.v1.ProvisionRequest\x1a1.practiceengine.orchestrator.v1.ProvisionResponse\x12j\n" +
	"\aConnect\x12..practiceengine.orchestrator.v1.ConnectRequest\x1a/.practiceengine.orchestrator.v1.ConnectResponse\x12m\n" +
	"\bSnapshot\x12/.practiceengine.orchestrator.v1.SnapshotRequest\x1a0.practiceengine.orchestrator.v1.SnapshotResponse\x12l\n" +
	"\aRestore\x12..practiceengine.orchestrator.v1.RestoreRequest\x1a1.practiceengine.orchestrator.v1.ProvisionResponse\x12\x8b\x01\n" +
	"\x18MintValidatorCredentials\x126.practiceengine.orchestrator.v1.MintCredentialsRequest\x1a7.practiceengine.orchestrator.v1.MintCredentialsResponse\x12j\n" +
	"\aDestroy\x12..practiceengine.orchestrator.v1.DestroyRequest\x1a/.practiceengine.orchestrator.v1.DestroyResponse\x12v\n" +
	"\vInjectFault\x122.practiceengine.orchestrator.v1.InjectFaultRequest\x1a3.practiceengine.orchestrator.v1.InjectFaultResponse\x12\x82\x01\n" +
	"\x0fCaptureBaseline\x126.practiceengine.orchestrator.v1.CaptureBaselineRequest\x1a7.practiceengine.orchestrator.v1.CaptureBaselineResponse\x12\x82\x01\n" +
	"\x0fCheckRegression\x126.practiceengine.orchestrator.v1.CheckRegressionRequest\x1a7.practiceengine.orchestrator.v1.CheckRegressionResponse\x12|\n" +
	"\rExecValidator\x124.practiceengine.orchestrator.v1.ExecValidatorRequest\x1a5.practiceengine.orchestrator.v1.ExecValidatorResponse\x12p\n" +
	"\tExecShell\x120.practiceengine.orchestrator.v1.ExecShellRequest\x1a1.practiceengine.orchestrator.v1.ExecShellResponseBNZLgithub.com/tanyasawarn/skillfyme-hands-on/orchestrator/pkg/pb;orchestratorv1b\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orchestrator_proto_goTypes = []any{
	(Tier)(0),                       // 0: practiceengine.orchestrator.v1.Tier
	(EnvironmentStatus)(0),          // 1: practiceengine.orchestrator.v1.EnvironmentStatus
	(*ResourceSpec)(nil),            // 2: practiceengine.orchestrator.v1.ResourceSpec
	(*FixtureRef)(nil),              // 3: practiceengine.orchestrator.v1.FixtureRef
	(*ProvisionRequest)(nil),        // 4: practiceengine.orchestrator.v1.ProvisionRequest
	(*ProvisionResponse)(nil),       // 5: practiceengine.orchestrator.v1.ProvisionResponse
	(*ConnectRequest)(nil),          // 6: practiceengine.orchestrator.v1.ConnectRequest
	(*ConnectResponse)(nil),         // 7: practiceengine.orchestrator.v1.ConnectResponse
	(*SnapshotRequest)(nil),         // 8: practiceengine.orchestrator.v1.SnapshotRequest
	(*SnapshotResponse)(nil),        // 9: practiceengine.orchestrator.v1.SnapshotResponse
	(*RestoreRequest)(nil),          // 10: practiceengine.orchestrator.v1.RestoreRequest
	(*MintCredentialsRequest)(nil),  // 11: practiceengine.orchestrator.v1.MintCredentialsRequest
	(*MintCredentialsResponse)(nil), // 12: practiceengine.orchestrator.v1.MintCredentialsResponse
	(*DestroyRequest)(nil),          // 13: practiceengine.orchestrator.v1.DestroyRequest
	(*DestroyResponse)(nil),         // 14: practiceengine.orchestrator.v1.DestroyResponse
	(*InjectFaultRequest)(nil),      // 15: practiceengine.orchestrator.v1.InjectFaultRequest
	(*InjectFaultResponse)(nil),     // 16: practiceengine.orchestrator.v1.InjectFaultResponse
	(*CaptureBaselineRequest)(nil),  // 17: practiceengine.orchestrator.v1.CaptureBaselineRequest
	(*CaptureBaselineResponse)(nil), // 18: practiceengine.orchestrator.v1.CaptureBaselineResponse
	(*CheckRegressionRequest)(nil),  // 19: practiceengine.orchestrator.v1.CheckRegressionRequest
	(*CheckRegressionResponse)(nil), // 20: practiceengine.orchestrator.v1.CheckRegressionResponse
	(*ExecValidatorRequest)(nil),    // 21: practiceengine.orchestrator.v1.ExecValidatorRequest
	(*ExecValidatorResponse)(nil),   // 22: practiceengine.orchestrator.v1.ExecValidatorResponse
	(*ExecShellRequest)(nil),        // 23: practiceengine.orchestrator.v1.ExecShellRequest
	(*ExecShellResponse)(nil),       // 24: practiceengine.orchestrator.v1.ExecShellResponse
	nil,                             // 25: practiceengine.orchestrator.v1.InjectFaultRequest.ParamsEntry
}
var file_orchestrator_proto_depIdxs = []int32{
	0,  // 0: practiceengine.orchestrator.v1.ProvisionRequest.tier:type_name -> practiceengine.orchestrator.v1.Tier
	2,  // 1: practiceengine.orchestrator.v1.ProvisionRequest.resources:type_name -> practiceengine.orchestrator.v1.ResourceSpec
	3,  // 2: practiceengine.orchestrator.v1.ProvisionRequest.fixtures:type_name -> practiceengine.orchestrator.v1.FixtureRef
	1,  // 3: practiceengine.orchestrator.v1.ProvisionResponse.status:type_name -> practiceengine.orchestrator.v1.EnvironmentStatus
	7,  // 4: practiceengine.orchestrator.v1.ProvisionResponse.endpoints:type_name -> practiceengine.orchestrator.v1.ConnectResponse
	0,  // 5: practiceengine.orchestrator.v1.RestoreRequest.tier:type_name -> practiceengine.orchestrator.v1.Tier
	2,  // 6: practiceengine.orchestrator.v1.RestoreRequest.resources:type_name -> practiceengine.orchestrator.v1.ResourceSpec
	25, // 7: practiceengine.orchestrator.v1.InjectFaultRequest.params:type_name -> practiceengine.orchestrator.v1.InjectFaultRequest.ParamsEntry
	4,  // 8: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Provision:input_type -> practiceengine.orchestrator.v1.ProvisionRequest
	6,  // 9: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Connect:input_type -> practiceengine.orchestrator.v1.ConnectRequest
	8,  // 10: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Snapshot:input_type -> practiceengine.orchestrator.v1.SnapshotRequest
	10, // 11: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Restore:input_type -> practiceengine.orchestrator.v1.RestoreRequest
	11, // 12: practiceengine.orchestrator.v1.EnvironmentOrchestrator.MintValidatorCredentials:input_type -> practiceengine.orchestrator.v1.MintCredentialsRequest
	13, // 13: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Destroy:input_type -> practiceengine.orchestrator.v1.DestroyRequest
	15, // 14: practiceengine.orchestrator.v1.EnvironmentOrchestrator.InjectFault:input_type -> practiceengine.orchestrator.v1.InjectFaultRequest
	17, // 15: practiceengine.orchestrator.v1.EnvironmentOrchestrator.CaptureBaseline:input_type -> practiceengine.orchestrator.v1.CaptureBaselineRequest
	19, // 16: practiceengine.orchestrator.v1.EnvironmentOrchestrator.CheckRegression:input_type -> practiceengine.orchestrator.v1.CheckRegressionRequest
	21, // 17: practiceengine.orchestrator.v1.EnvironmentOrchestrator.ExecValidator:input_type -> practiceengine.orchestrator.v1.ExecValidatorRequest
	23, // 18: practiceengine.orchestrator.v1.EnvironmentOrchestrator.ExecShell:input_type -> practiceengine.orchestrator.v1.ExecShellRequest
	5,  // 19: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Provision:output_type -> practiceengine.orchestrator.v1.ProvisionResponse
	7,  // 20: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Connect:output_type -> practiceengine.orchestrator.v1.ConnectResponse
	9,  // 21: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Snapshot:output_type -> practiceengine.orchestrator.v1.SnapshotResponse
	5,  // 22: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Restore:output_type -> practiceengine.orchestrator.v1.ProvisionResponse
	12, // 23: practiceengine.orchestrator.v1.EnvironmentOrchestrator.MintValidatorCredentials:output_type -> practiceengine.orchestrator.v1.MintCredentialsResponse
	14, // 24: practiceengine.orchestrator.v1.EnvironmentOrchestrator.Destroy:output_type -> practiceengine.orchestrator.v1.DestroyResponse
	16, // 25: practiceengine.orchestrator.v1.EnvironmentOrchestrator.InjectFault:output_type -> practiceengine.orchestrator.v1.InjectFaultResponse
	18, // 26: practiceengine.orchestrator.v1.EnvironmentOrchestrator.CaptureBaseline:output_type -> practiceengine.orchestrator.v1.CaptureBaselineResponse
	20, // 27: practiceengine.orchestrator.v1.EnvironmentOrchestrator.CheckRegression:output_type -> practiceengine.orchestrator.v1.CheckRegressionResponse
	22, // 28: practiceengine.orchestrator.v1.EnvironmentOrchestrator.ExecValidator:output_type -> practiceengine.orchestrator.v1.ExecValidatorResponse
	24, // 29: practiceengine.orchestrator.v1.EnvironmentOrchestrator.ExecShell:output_type -> practiceengine.orchestrator.v1.ExecShellResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
