// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: orchestrator.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvironmentOrchestrator_Provision_FullMethodName                = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/Provision"
	EnvironmentOrchestrator_Connect_FullMethodName                  = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/Connect"
	EnvironmentOrchestrator_Snapshot_FullMethodName                 = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/Snapshot"
	EnvironmentOrchestrator_Restore_FullMethodName                  = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/Restore"
	EnvironmentOrchestrator_MintValidatorCredentials_FullMethodName = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/MintValidatorCredentials"
	EnvironmentOrchestrator_Destroy_FullMethodName                  = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/Destroy"
	EnvironmentOrchestrator_InjectFault_FullMethodName              = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/InjectFault"
	EnvironmentOrchestrator_CaptureBaseline_FullMethodName          = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/CaptureBaseline"
	EnvironmentOrchestrator_CheckRegression_FullMethodName          = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/CheckRegression"
	EnvironmentOrchestrator_ExecValidator_FullMethodName            = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/ExecValidator"
	EnvironmentOrchestrator_ExecShell_FullMethodName                = "/practiceengine.orchestrator.v1.EnvironmentOrchestrator/ExecShell"
)

// EnvironmentOrchestratorClient is the client API for EnvironmentOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnvironmentOrchestrator is the sole synchronous entry point into the
// Environment Orchestrator service (Dev A, Go). Practice Core (Dev B) never
// talks to the execution fabric directly — everything goes through this
// contract. See doc §5.1, §5.5, §8.1, §8.2.
type EnvironmentOrchestratorClient interface {
	// Provision requests a new environment for an attempt. Long-running:
	// returns immediately with status=PROVISIONING: the caller subscribes to
	// env.* events (see events.md) for READY/FAILED, mirroring the doc's
	// "Operation, not a blocked request" API principle (§8.3).
	Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error)
	// Connect returns live connection endpoints (terminal WS, editor, preview)
	// for an already-READY environment.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Snapshot forces an out-of-cycle workspace snapshot (in addition to the
	// periodic 5-min snapshot). Used before RESET_ALL, on suspend, on TTL/idle.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Restore provisions a fresh environment and restores the given snapshot
	// into it (RESET_KEEP_FILES, resume-from-suspend). §4.1, §5.5.
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*ProvisionResponse, error)
	// Validate is NOT how validators run (that's Dev B's Validator Runner
	// executing against minted credentials) — this RPC exists only to mint
	// short-lived read-only credentials scoped to one environment, per the
	// MintValidatorCredentials integration point in PLAN.md Phase 1 #2.
	MintValidatorCredentials(ctx context.Context, in *MintCredentialsRequest, opts ...grpc.CallOption) (*MintCredentialsResponse, error)
	// Destroy tears down an environment immediately. Idempotent — destroying
	// an already-destroyed environment is a no-op success, never an error.
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	// InjectFault applies a fault manifest to an already-healthy environment.
	// Phase 2 integration point (PLAN.md Phase 2) — included now so the
	// contract doesn't need a breaking change later.
	InjectFault(ctx context.Context, in *InjectFaultRequest, opts ...grpc.CallOption) (*InjectFaultResponse, error)
	// CaptureBaseline and CheckRegression back the NO_REGRESSION validator
	// type (doc §6.2, §7.3 step 3: "Capture full resource inventory +
	// health matrix. This is the NO_REGRESSION reference"). Narrow,
	// purpose-built RPCs rather than the doc's eventual design (Dev B
	// executing this itself via MintValidatorCredentials) -- that
	// credential-minting path isn't implemented yet, same pragmatic
	// "swap it in later" precedent as InjectFault taking this shortcut
	// ahead of a fuller mechanism.
	CaptureBaseline(ctx context.Context, in *CaptureBaselineRequest, opts ...grpc.CallOption) (*CaptureBaselineResponse, error)
	CheckRegression(ctx context.Context, in *CheckRegressionRequest, opts ...grpc.CallOption) (*CheckRegressionResponse, error)
	// ExecValidator replaces Dev B's FakeValidatorExecutor for the 6
	// validator types the published lab content actually uses
	// (SHELL_ASSERT, SHELL_JSON, FILE_EXISTS, FILE_CONTENT, FILE_PARSE,
	// K8S_ASSERT). Same pragmatic shortcut as InjectFault/CaptureBaseline:
	// the doc's real design has Dev B executing validators itself via
	// MintValidatorCredentials, which isn't implemented -- SHELL_*/FILE_*
	// types exec inside the workspace pod (no cluster credentials needed,
	// same non-interactive exec pattern as the session broker's telemetry
	// hook install); K8S_ASSERT executes via the orchestrator's own K8s API
	// access, since the workspace pod itself has no kubectl or cluster
	// credentials (confirmed gap, same one InjectFault/CaptureBaseline hit).
	ExecValidator(ctx context.Context, in *ExecValidatorRequest, opts ...grpc.CallOption) (*ExecValidatorResponse, error)
	// ExecShell runs an arbitrary command inside the workspace pod and
	// returns its raw output, unlike ExecValidator which only reports a
	// PASS/FAIL/ERROR verdict. Built for the content-CI golden-path harness
	// (PLAN.md M1.3): applying an authored reference_solution's
	// solution_apply script needs the command to actually run and mutate
	// pod state, not be evaluated as an assertion. Same execInPod mechanism
	// ExecValidator's SHELL_* types already use.
	ExecShell(ctx context.Context, in *ExecShellRequest, opts ...grpc.CallOption) (*ExecShellResponse, error)
}

type environmentOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvironmentOrchestratorClient(cc grpc.ClientConnInterface) EnvironmentOrchestratorClient {
	return &environmentOrchestratorClient{cc}
}

func (c *environmentOrchestratorClient) Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_Provision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) MintValidatorCredentials(ctx context.Context, in *MintCredentialsRequest, opts ...grpc.CallOption) (*MintCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintCredentialsResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_MintValidatorCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) InjectFault(ctx context.Context, in *InjectFaultRequest, opts ...grpc.CallOption) (*InjectFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectFaultResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_InjectFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) CaptureBaseline(ctx context.Context, in *CaptureBaselineRequest, opts ...grpc.CallOption) (*CaptureBaselineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureBaselineResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_CaptureBaseline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) CheckRegression(ctx context.Context, in *CheckRegressionRequest, opts ...grpc.CallOption) (*CheckRegressionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRegressionResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_CheckRegression_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) ExecValidator(ctx context.Context, in *ExecValidatorRequest, opts ...grpc.CallOption) (*ExecValidatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecValidatorResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_ExecValidator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentOrchestratorClient) ExecShell(ctx context.Context, in *ExecShellRequest, opts ...grpc.CallOption) (*ExecShellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecShellResponse)
	err := c.cc.Invoke(ctx, EnvironmentOrchestrator_ExecShell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvironmentOrchestratorServer is the server API for EnvironmentOrchestrator service.
// All implementations must embed UnimplementedEnvironmentOrchestratorServer
// for forward compatibility.
//
// EnvironmentOrchestrator is the sole synchronous entry point into the
// Environment Orchestrator service (Dev A, Go). Practice Core (Dev B) never
// talks to the execution fabric directly — everything goes through this
// contract. See doc §5.1, §5.5, §8.1, §8.2.
type EnvironmentOrchestratorServer interface {
	// Provision requests a new environment for an attempt. Long-running:
	// returns immediately with status=PROVISIONING: the caller subscribes to
	// env.* events (see events.md) for READY/FAILED, mirroring the doc's
	// "Operation, not a blocked request" API principle (§8.3).
	Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error)
	// Connect returns live connection endpoints (terminal WS, editor, preview)
	// for an already-READY environment.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Snapshot forces an out-of-cycle workspace snapshot (in addition to the
	// periodic 5-min snapshot). Used before RESET_ALL, on suspend, on TTL/idle.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Restore provisions a fresh environment and restores the given snapshot
	// into it (RESET_KEEP_FILES, resume-from-suspend). §4.1, §5.5.
	Restore(context.Context, *RestoreRequest) (*ProvisionResponse, error)
	// Validate is NOT how validators run (that's Dev B's Validator Runner
	// executing against minted credentials) — this RPC exists only to mint
	// short-lived read-only credentials scoped to one environment, per the
	// MintValidatorCredentials integration point in PLAN.md Phase 1 #2.
	MintValidatorCredentials(context.Context, *MintCredentialsRequest) (*MintCredentialsResponse, error)
	// Destroy tears down an environment immediately. Idempotent — destroying
	// an already-destroyed environment is a no-op success, never an error.
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	// InjectFault applies a fault manifest to an already-healthy environment.
	// Phase 2 integration point (PLAN.md Phase 2) — included now so the
	// contract doesn't need a breaking change later.
	InjectFault(context.Context, *InjectFaultRequest) (*InjectFaultResponse, error)
	// CaptureBaseline and CheckRegression back the NO_REGRESSION validator
	// type (doc §6.2, §7.3 step 3: "Capture full resource inventory +
	// health matrix. This is the NO_REGRESSION reference"). Narrow,
	// purpose-built RPCs rather than the doc's eventual design (Dev B
	// executing this itself via MintValidatorCredentials) -- that
	// credential-minting path isn't implemented yet, same pragmatic
	// "swap it in later" precedent as InjectFault taking this shortcut
	// ahead of a fuller mechanism.
	CaptureBaseline(context.Context, *CaptureBaselineRequest) (*CaptureBaselineResponse, error)
	CheckRegression(context.Context, *CheckRegressionRequest) (*CheckRegressionResponse, error)
	// ExecValidator replaces Dev B's FakeValidatorExecutor for the 6
	// validator types the published lab content actually uses
	// (SHELL_ASSERT, SHELL_JSON, FILE_EXISTS, FILE_CONTENT, FILE_PARSE,
	// K8S_ASSERT). Same pragmatic shortcut as InjectFault/CaptureBaseline:
	// the doc's real design has Dev B executing validators itself via
	// MintValidatorCredentials, which isn't implemented -- SHELL_*/FILE_*
	// types exec inside the workspace pod (no cluster credentials needed,
	// same non-interactive exec pattern as the session broker's telemetry
	// hook install); K8S_ASSERT executes via the orchestrator's own K8s API
	// access, since the workspace pod itself has no kubectl or cluster
	// credentials (confirmed gap, same one InjectFault/CaptureBaseline hit).
	ExecValidator(context.Context, *ExecValidatorRequest) (*ExecValidatorResponse, error)
	// ExecShell runs an arbitrary command inside the workspace pod and
	// returns its raw output, unlike ExecValidator which only reports a
	// PASS/FAIL/ERROR verdict. Built for the content-CI golden-path harness
	// (PLAN.md M1.3): applying an authored reference_solution's
	// solution_apply script needs the command to actually run and mutate
	// pod state, not be evaluated as an assertion. Same execInPod mechanism
	// ExecValidator's SHELL_* types already use.
	ExecShell(context.Context, *ExecShellRequest) (*ExecShellResponse, error)
	mustEmbedUnimplementedEnvironmentOrchestratorServer()
}

// UnimplementedEnvironmentOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvironmentOrchestratorServer struct{}

func (UnimplementedEnvironmentOrchestratorServer) Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) Restore(context.Context, *RestoreRequest) (*ProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) MintValidatorCredentials(context.Context, *MintCredentialsRequest) (*MintCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintValidatorCredentials not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) InjectFault(context.Context, *InjectFaultRequest) (*InjectFaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectFault not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) CaptureBaseline(context.Context, *CaptureBaselineRequest) (*CaptureBaselineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureBaseline not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) CheckRegression(context.Context, *CheckRegressionRequest) (*CheckRegressionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRegression not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) ExecValidator(context.Context, *ExecValidatorRequest) (*ExecValidatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecValidator not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) ExecShell(context.Context, *ExecShellRequest) (*ExecShellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecShell not implemented")
}
func (UnimplementedEnvironmentOrchestratorServer) mustEmbedUnimplementedEnvironmentOrchestratorServer() {
}
func (UnimplementedEnvironmentOrchestratorServer) testEmbeddedByValue() {}

// UnsafeEnvironmentOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvironmentOrchestratorServer will
// result in compilation errors.
type UnsafeEnvironmentOrchestratorServer interface {
	mustEmbedUnimplementedEnvironmentOrchestratorServer()
}

func RegisterEnvironmentOrchestratorServer(s grpc.ServiceRegistrar, srv EnvironmentOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedEnvironmentOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvironmentOrchestrator_ServiceDesc, srv)
}

func _EnvironmentOrchestrator_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_Provision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).Provision(ctx, req.(*ProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_MintValidatorCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).MintValidatorCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_MintValidatorCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).MintValidatorCredentials(ctx, req.(*MintCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_InjectFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).InjectFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_InjectFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).InjectFault(ctx, req.(*InjectFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_CaptureBaseline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureBaselineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).CaptureBaseline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_CaptureBaseline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).CaptureBaseline(ctx, req.(*CaptureBaselineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_CheckRegression_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRegressionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).CheckRegression(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_CheckRegression_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).CheckRegression(ctx, req.(*CheckRegressionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_ExecValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).ExecValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_ExecValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).ExecValidator(ctx, req.(*ExecValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentOrchestrator_ExecShell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecShellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentOrchestratorServer).ExecShell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentOrchestrator_ExecShell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentOrchestratorServer).ExecShell(ctx, req.(*ExecShellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvironmentOrchestrator_ServiceDesc is the grpc.ServiceDesc for EnvironmentOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvironmentOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "practiceengine.orchestrator.v1.EnvironmentOrchestrator",
	HandlerType: (*EnvironmentOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provision",
			Handler:    _EnvironmentOrchestrator_Provision_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _EnvironmentOrchestrator_Connect_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _EnvironmentOrchestrator_Snapshot_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _EnvironmentOrchestrator_Restore_Handler,
		},
		{
			MethodName: "MintValidatorCredentials",
			Handler:    _EnvironmentOrchestrator_MintValidatorCredentials_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _EnvironmentOrchestrator_Destroy_Handler,
		},
		{
			MethodName: "InjectFault",
			Handler:    _EnvironmentOrchestrator_InjectFault_Handler,
		},
		{
			MethodName: "CaptureBaseline",
			Handler:    _EnvironmentOrchestrator_CaptureBaseline_Handler,
		},
		{
			MethodName: "CheckRegression",
			Handler:    _EnvironmentOrchestrator_CheckRegression_Handler,
		},
		{
			MethodName: "ExecValidator",
			Handler:    _EnvironmentOrchestrator_ExecValidator_Handler,
		},
		{
			MethodName: "ExecShell",
			Handler:    _EnvironmentOrchestrator_ExecShell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
